version: '3.8'

services:
  api-load:
    build: ./ChromaDBLoad
    ports:
      - "8000:8000"
    networks:
      - app-network

  api-embeddings:
    build: ./ChromaEmbeddingsPool
    ports:
      - "8001:8001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
